version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - appnet

  auth-service:
    build:
      dockerfile: services/authService/dockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
    env_file:
      - ./.env
    ports:
      - "5085:5085"
    depends_on:
      - rabbitmq
    networks:
      - appnet

  user-service:
    build:
      dockerfile: services/userService/Dockerfile
    ports:
      - "5082:5082"
    depends_on:
      - rabbitmq
    networks:
      - appnet
    env_file:
      - ./.env

networks:
  appnet:
    driver: bridge