services:
  userdb:
    platform: linux/arm64
    image: mongo:7.0-jammy
    container_name: gethub-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: UserServiceDb
    ports:
      - "27017:27017"
    volumes:
      - userdb_mongodb_data:/data/db
      - userdb_mongodb_config:/data/configdb
    networks:
      - appnet
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    networks:
      - appnet

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: gethub-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass123
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost # for development only, change to keycloak in production
      KC_HOSTNAME_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - keycloakdb
    networks:
      - appnet
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  keycloakdb:
    platform: linux/arm64
    image: postgres:16-alpine
    container_name: gethub-keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass123
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: unless-stopped

  api-gateway:
    build:
      dockerfile: services/apiGateway/Dockerfile
    env_file:
      - ./.env
      - services/apiGateway/.env
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - user-service
    networks:
      - appnet

  user-service:
    build:
      dockerfile: services/userService/Dockerfile
    ports:
      - "5082:5082"
    depends_on:
      userdb:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - appnet
    env_file:
      - ./.env
      - services/userService/.env
    restart: unless-stopped

volumes:
  userdb_mongodb_data:
    driver: local
  userdb_mongodb_config:
    driver: local
  # catalog_postgres_data:
  #   driver: local
  keycloak_postgres_data:
    driver: local
  keycloak_data:
    driver: local
  seq_data:
    driver: local

networks:
  appnet:
    driver: bridge